# Text Representation

In [1]:
# 1. Bag of words
# we use countvectorizer

In [2]:
import pandas as pd
import numpy as np

In [17]:
df=pd.DataFrame({'text':['people watch cricket','player was player','cricket play comment','people write comment'],'output':[1,1,0,0]})

In [18]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  cricket play comment       0
3  people write comment       0

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv=CountVectorizer()

In [21]:
bow=cv.fit_transform(df['text'])

In [22]:
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'play': 3, 'comment': 0, 'write': 7}


In [23]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [24]:
cv.transform(["Cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [25]:
#2.N grams

In [26]:
v=CountVectorizer(ngram_range=(1,2))

In [27]:
bow=v.fit_transform(df['text'])

In [28]:
df['text']

0    people watch cricket
1       player was player
2    cricket play comment
3    people write comment
Name: text, dtype: object

In [29]:
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'play': 6, 'comment': 0, 'cricket play': 2, 'play comment': 7, 'write': 14, 'people write': 5, 'write comment': 15}


In [30]:
# TF (Term Frequency)
# IDF (Inverse Document Frequency)

In [31]:
# TF(t,d) = (number of occurences of term t in document d)/(Total number of terms in the document d)

#example: 
#d1 = people  watch cricket

#tf(people,d1)=1/3

#d2= match was match

# tf(match,d2)=2/3

In [32]:
# IDF(t) = loge(total number of documents in the corpus)/(number of documents with term t in them)
#here corpus means number of sentences

#example :
#d1 = people watch cricket
#d2 = cricket was cricket
#d3 = people write comment
#d4 = cricket write comment

# idf(cricket)


In [33]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  cricket play comment       0
3  people write comment       0

In [38]:
# we can use this by apply feature_extraction method in sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854]])

In [41]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']
